import java.io.*;
import bicycle.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/*
 * StoreGUI.java
 *
 * Created on 26-Nov-2009, 12:01:43 AM
 */
/**
 *
 * @author zeeshan
 */
public class StoreGUI extends javax.swing.JFrame {
  BicycleStore  myStore;

  /** Creates new form StoreGUI */
  public StoreGUI() {
    myStore = new BicycleStore();
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    bLoad = new javax.swing.JButton();
    bSearch = new javax.swing.JButton();
    bSort = new javax.swing.JButton();
    tInput = new javax.swing.JTextField();
    jScrollOutput = new javax.swing.JScrollPane();
    tOutput = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    bLoad.setText("Load Catalouge");
    bLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bLoadActionPerformed(evt);
      }
    });

    bSearch.setText("Search User");
    bSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bSearchActionPerformed(evt);
      }
    });

    bSort.setText("Sort By Name");
    bSort.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bSortActionPerformed(evt);
      }
    });

    tInput.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(bLoad)
            .addGap(18, 18, 18)
            .addComponent(bSearch)
            .addGap(18, 18, 18)
            .addComponent(bSort))
          .addComponent(tInput, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bLoad)
          .addComponent(bSearch)
          .addComponent(bSort))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(tInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(9, 9, 9))
    );

    tOutput.setColumns(20);
    tOutput.setEditable(false);
    tOutput.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    tOutput.setRows(5);
    jScrollOutput.setViewportView(tOutput);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(jScrollOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        .addGap(12, 12, 12))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void bLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoadActionPerformed
      if (!(myStore.loadCatalouge())) {
        tOutput.setText("Could not open the file " + System.getProperty("java.class.path").substring(0, System.getProperty("java.class.path").lastIndexOf(System.getProperty("file.separator")) + 1) + myStore.ordersFile + " for Reading \n");
        return;
      }

      String output = "";
      for (Map.Entry<String, ArrayList<Bicycle>> element : myStore.ordersList.entrySet()) {
        output += "Catalouge for : " + element.getKey() + "\n";
        for (Bicycle e : element.getValue()) {
          output += "  " + e + "\n";
        }
        output += "\n";
      }

      tOutput.setText(output);
    }//GEN-LAST:event_bLoadActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
      String clientName = tInput.getText();
      String output = "";

      if (clientName.isEmpty()) {
        tOutput.setText("Enter a name to search for!! \n");
        return;
      }

      if (myStore.ordersList.containsKey(clientName)) {
        output += "catalouge for: " + clientName + "\n";
        for (Bicycle e : myStore.ordersList.get(clientName)) {
          output += "  " + e + "\n";
        }
      } else {
        output += "No orders from " + clientName + "!!";
      }

      tOutput.setText(output);
    }//GEN-LAST:event_bSearchActionPerformed

    private void bSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSortActionPerformed
      String output = "";

      ArrayList<String> sortedNames = new ArrayList<String>(myStore.ordersList.keySet());
      Collections.sort(sortedNames);

      for (String element : sortedNames) {
        output += "Catalouge for : " + element + "\n";
        for (Bicycle e : myStore.ordersList.get(element)) {
          output += "  " + e + "\n";
        }
        output += "\n";
      }

      tOutput.setText(output);
    }//GEN-LAST:event_bSortActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new StoreGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bLoad;
  private javax.swing.JButton bSearch;
  private javax.swing.JButton bSort;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollOutput;
  private javax.swing.JTextField tInput;
  private javax.swing.JTextArea tOutput;
  // End of variables declaration//GEN-END:variables
}
